
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-02T20:13:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d378c12610a598f36d2422fa465a3199942d8945",
 "version": "1.13.3+6.gd378c12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
